kBootstrap: docker
From: spack/ubuntu-bionic

%labels
    MAINTAINER icaoberg
    EMAIL icaoberg@psc.edu
    WEBSITE http://github.com/pscedu/singularity-flac
    COPYRIGHT Copyright © 2025 Pittsburgh Supercomputing Center. All Rights Reserved.
    VERSION 1.4.3

%environment
    export PATH=/opt/spack/bin/:$PATH
    . /opt/spack/share/spack/setup-env.sh
    spack load flac@1.4.3

%post
    export PATH=/opt/spack/bin/:$PATH
    apt-get update
    . /opt/spack/share/spack/setup-env.sh
    spack install flac@1.4.3

%runscript
    #!/bin/bash
    export PATH=/opt/spack/bin/:$PATH
    . /opt/spack/share/spack/setup-env.sh
    spack load flac@1.4.3
    exec flac "$@"
